swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
  <img src=https://expertsensi.xss.ht>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
